---
name: CarsellonaDaily
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  flutter_statusbarcolor: ^0.2.3
  cached_network_image: ^2.4.1
  flutter_slidable: ^0.5.7
  google_fonts: ^1.1.1
  table_calendar: ^2.3.2
  flutter_neumorphic: ^3.0.3
  flutter_stack_card: ^0.2.0+1
  clay_containers: ^0.2.2
  nb_utils: ^3.3.0+2
  random_color: ^1.0.5
  charts_flutter: ^0.9.0
  percent_indicator: ^2.1.8
  snaplist: ^0.1.8
  get: ^3.24.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
  - images/
